title           : Gaspare Sganga
description     : Software Developer. GIS & Web Mapping expert at Setin.
author          : Gaspare Sganga
production_url  : https://gasparesganga.com
development_url : https://test.gasparesganga.com
social          :
  disqus    : gasparesganga
  feed      : /feed.xml
  github    : https://github.com/gasparesganga
  paypal    : https://paypal.me/gasparesganga
  twitter   : https://twitter.com/gasparesganga

future          : true
paginate        : 10
paginate_path   : /posts/page:num
permalink       : /posts/:title/

markdown        : kramdown
kramdown        :
  input                 : GFM
  hard_wrap             : true
  syntax_highlighter    : rouge
highlighter     : rouge

include :
  - .htaccess

exclude :
  - .asset-cache
  - browserslist
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

plugins :
  - jekyll-assets
  - jekyll-paginate
  - autoprefixer-rails
  - uglifier

assets : 
  sources       : [_assets, labs]
  assets        : ["[^_]*(?!_assets\\/).*"]
  destination   : "/assets"
  digest        : true
  source_maps   : false
  #compression   : true
  compression   : false
  gzip          : false
  defaults      :
    js  : { integrity: true, crossorigin: false }
    css : { integrity: true, crossorigin: false }
    img : { integrity: true, crossorigin: false }
  caching       :
    type    : memory
    enabled : true
  precompile    : []
  plugins       :
    css : { autoprefixer: {}}
